### ISSUE TITLE
Lumo drawer toggle has arbitrary size and doesn't look nice

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-app-layout#110]
This is the issue similar to #106 but now for Lumo.

Let me suggest an improvement which is expected to make drawer toggle look better.

```css
:host {
  width: var(--lumo-size-l);
  height: var(--lumo-size-l);
  min-width: auto;
  margin: 0 var(--lumo-space-m);
  padding: 0;
  background: transparent;
}
```

See the original code in my [webpack starter](https://github.com/web-padawan/polymer3-webpack-starter/blob/00d840f2bfe8eaec5805863d861d713f7cc878b5/src/styles/layout-styles.js#L29-L36).

Will submit a PR and update visual tests accordingly.
