### ISSUE TITLE
Add listener to overlay property

### ISSUE THREAD

**Issue by Firestorm87** [vaadin/vaadin-app-layout#123]
The App-Layout has some fixed widths to switch the overlay-mode.

e.g.
>       @media (max-width: 800px),
>       (max-height: 600px) {
>         :host {
>           --vaadin-app-layout-drawer-overlay: true;
>         }
>         [part="drawer"] {
>           width: 20em;
>         }
>       }

On Java-Side there is just a method to check if the overlay is active:
>     /**
>      *  <strong>Note:</strong> This property is controlled via CSS and can not be changed directly.
>      *
>      * @return {@code true} if drawer is an overlay on top of the content. {@code false} otherwise.
>      */
>     @Synchronize("overlay-changed")
>     public boolean isOverlay() {
>         return overlayProperty.get(this);
>     }

Some times i would like to get informed if this variable is changing.
For example to hide the drawer-toggle-button.

My current workaround is to call UI.getCurrent().page.retrieveExtendedClientDetails and listenen for UI.getCurrent().page.addBrowserWindowResizeListener.
But therefore i need to check the fixed values for max 800 and max 600 pixels.

**Comment by lkraav** [comment]
Curious, why wasn't `<vaadin-device-detector>` strategy used here? (It seems to be used in no other component than <vaadin-context-menu>)

https://github.com/vaadin/vaadin-context-menu/blob/v4.3.12/src/vaadin-device-detector.html

It indeed creates a dependency on `<iron-media-query>`, but after using it, it's been quite nice to have state viewport width reflected into component attributes easily.

Maybe @jouni @web-padawan know if there will be a more uniform "responsive" strategy by Vaadin 15, or is it even on the table?

**Comment by web-padawan** [comment]
> why wasn't <vaadin-device-detector> strategy used here? (It seems to be used in no other component than <vaadin-context-menu>)

At some point I proposed to do this kind of refactoring. It is on my personal list of the "nice to have" tasks that I would like to approach while working on the LitElement migration.

**Comment by jouni** [comment]
The `overlay` property is already reflected as an attribute on the App Layout element. You should be able to use that to control the visibility of Drawer Toggle. For example:

```css
vaadin-app-layout[overlay] vaadin-drawer-toggle {
  display: none;
}
```

I would avoid controlling the visibility from the server/Java, as it’ll make it slower to respond to changes. The initial rendering of the layout could also be different (i.e. you see the drawer toggle briefly during page load before it disappears).

A longer explanation follows. I ended up writing it before I remembered that the attribute is already there which you can use 😄 

----

One option is to use the same media query in your own CSS (copy-paste) to control the visibility of the drawer toggle.

You can control the exact media query yourself from CSS, if you want to be sure it stays in sync with App Layout (if for some reason the internal media query changes in the future).

You can write custom CSS in your app that overrides the built-in media queries. For example:

```css
@media (min-width: 801px), (min-height: 601px) {
  vaadin-app-layout {
    --vaadin-app-layout-drawer-overlay: false;
  }

  vaadin-drawer-toggle {
    display: none;
  }
}

@media (max-width: 800px) and (max-height: 600px) {
  vaadin-app-layout {
    --vaadin-app-layout-drawer-overlay: true;
  }
}
```

I have no objections using media queries in JS in general. Though, we should avoid using iron-media-query if possible because of the dependency to legacy Polymer, and use the native JS API instead.

The problem I have with them is that they can prevent a theme developer/designer from controlling all styling with CSS, and they would have to dive into JS as well (if there’s an API to control it). And then those two can start get out of sync if you’re not careful.

The queries should be shared from CSS to JS so that full styling control remains on the CSS side. CSS custom properties would fit the purpose. For example (not working code):

```css
vaadin-app-layout {
  --vaadin-app-layout-drawer-overlay-media: (max-width: 800px) and (max-height: 600px);
}
```

This way the media queries are more easily co-located in the same file and you remember to update them together.
