### ISSUE TITLE
Inheritance is not supported for `--vaadin-app-layout-navbar-height`

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-app-layout#28]
Custom CSS properties are expected to inherit, i. e.:

```css
:root {
  --vaadin-app-layout-navbar-height: 100px;
}
```

should result in 100px navbar.

Actual: not inherited, results in default height instead.

**Comment by platosha** [comment]
I would suggest to use a fallback value, instead of defining the property on the `:host`:

```css
[part="navbar"] {
  height: var(--vaadin-app-layout-navbar-height, 50px);
}
```
