### ISSUE TITLE
CSS Rule destroys pointer events on touch devices.

### ISSUE THREAD

**Issue by sus-mharder** [vaadin/vaadin-app-layout#61]
I have a `<canvas>` element behind the `<vaadin-app-layout>` slot.
On a touch device, the canvas will only get `pointerdown` events. `pointermove` and `pointerup` events won't get called. When the canvas is located outside of the slot, the events work fine.

I do not understand why, but it seems that the `overflow:auto` rule on `div[part="content"]` seems to cause the issue.

```css
[part="content"] {
   flex: auto;
   height: 100%;
   /* overflow: auto; */
   -webkit-overflow-scrolling: touch;
}
```
In my case replacing the overflow with `height: -webkit-fill-available; height: -moz-fill-available; fill-available` solved the issue without changing the ui.
But i didn't check that on other examples.
